const escola = " Cod3r"
console.log(escola.charAt(5))
console.log(escola.charAt(6))
console.log(escola.charCodeAt(4))
console.log(escola.indexOf('4'))
console.log(escola.substring(2))
console.log(escola.substring(0,4))
console.log('Escola'.concat(escola).concat("!"))
console.log(escola.replace(3, 'e'))
console.log('Ana,Maria,Pedro'.split(','))